const assets = [
	{
	"id":"entities",
	"url":"assets/json\\entities.json"
	},
	{
	"id":"baseGameConfig",
	"url":"assets/json\\baseGameConfig.json"
	},
	{
	"id":"resources",
	"url":"assets/json\\resources.json"
	},
	{
	"id":"modifyers",
	"url":"assets/json\\modifyers.json"
	},
	{
	"id":"fiveLetters_",
	"url":"assets/json\\fiveLetters_.json"
	},
	{
	"id":"fourLetters_",
	"url":"assets/json\\fourLetters_.json"
	},
	{
	"id":"sixLetters_",
	"url":"assets/json\\sixLetters_.json"
	},
	{
	"id":"worduoConfig",
	"url":"assets/json\\worduoConfig.json"
	},
	{
	"id":"threeLetters_",
	"url":"assets/json\\threeLetters_.json"
	},
	{
	"id":"scrabble",
	"url":"assets/json\\scrabble.json"
	}
];

export default assets;
