const assets = [
	{
	"id":"dream1",
	"url":"assets/audio\\dream1.mp3"
	},
	{
	"id":"dream2",
	"url":"assets/audio\\dream2.mp3"
	},
	{
	"id":"Assets_Audio_dashSimple",
	"url":"assets/audio\\fx\\Assets_Audio_dashSimple.mp3"
	},
	{
	"id":"coins_04",
	"url":"assets/audio\\fx\\coins_04.mp3"
	},
	{
	"id":"dropTile",
	"url":"assets/audio\\fx\\dropTile.mp3"
	},
	{
	"id":"getCrazyOne",
	"url":"assets/audio\\fx\\getCrazyOne.mp3"
	},
	{
	"id":"getstar",
	"url":"assets/audio\\fx\\getstar.mp3"
	},
	{
	"id":"Harp-Flutter-02",
	"url":"assets/audio\\fx\\Harp-Flutter-02.mp3"
	},
	{
	"id":"item",
	"url":"assets/audio\\fx\\item.mp3"
	},
	{
	"id":"getThemAll",
	"url":"assets/audio\\fx\\getThemAll.mp3"
	},
	{
	"id":"kill",
	"url":"assets/audio\\fx\\kill.mp3"
	},
	{
	"id":"magic",
	"url":"assets/audio\\fx\\magic.mp3"
	},
	{
	"id":"Musical-Beep-Loop-02",
	"url":"assets/audio\\fx\\Musical-Beep-Loop-02.mp3"
	},
	{
	"id":"place",
	"url":"assets/audio\\fx\\place.mp3"
	},
	{
	"id":"Ping-Slide-Down",
	"url":"assets/audio\\fx\\Ping-Slide-Down.mp3"
	},
	{
	"id":"place2",
	"url":"assets/audio\\fx\\place2.mp3"
	},
	{
	"id":"place3",
	"url":"assets/audio\\fx\\place3.mp3"
	},
	{
	"id":"Pop-Musical",
	"url":"assets/audio\\fx\\Pop-Musical.mp3"
	},
	{
	"id":"Pop-Low-Pitch-Up-02",
	"url":"assets/audio\\fx\\Pop-Low-Pitch-Up-02.mp3"
	},
	{
	"id":"Pop-Tone",
	"url":"assets/audio\\fx\\Pop-Tone.mp3"
	},
	{
	"id":"pop",
	"url":"assets/audio\\fx\\pop.mp3"
	},
	{
	"id":"pop2",
	"url":"assets/audio\\fx\\pop2.mp3"
	},
	{
	"id":"shoosh",
	"url":"assets/audio\\fx\\shoosh.mp3"
	},
	{
	"id":"Tap-01",
	"url":"assets/audio\\fx\\Tap-01.mp3"
	},
	{
	"id":"teleport",
	"url":"assets/audio\\fx\\teleport.mp3"
	},
	{
	"id":"Whoosh",
	"url":"assets/audio\\fx\\Whoosh.mp3"
	}
];

export default assets;
